### ISSUE TITLE
fix mempool (is not) in transactions

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#44]
**Prerequisites**
 - [x] Did you perform a cursory search?
 - [x] Are you running the latest version?

**Describe the bug**
transaction list does not contain mempool transactions - like the one I just sent.

**Expected behavior**
this is most noticeable when sending a transaction. I send it, but the transaction doesn't show up in the transaction list. I think it should show up immediately

**Smartphone (please complete the following information):**
all

**Additional context**
This has been "solved" but it could be improved. It does now show up in the transaction list, but its not immediate. when we send, the electrum server notices and notifies us that one of our addresses had an updated status, we get the message and download all transactions for that address (even mempool ones), saving them again. then it shows up on the transaction list.

this was solution was built as an additional layer that satisfies "we need a mempool service - we don't get notified when something that was in the mempool becomes a real transaction, so we're getting the latest block header we need to attach a trigger to that waiter that says, 'if you have any mempool transactions - go download them again and update the records'" (from #6)

So there's a few second delay while the standard loop to electrum server happens. But then it does show up. This is an expedient solution, but what would be more ideal on the front end is to keep a list of all transactions we made that have not been downloaded yet, (then remove them once they're download) and include that list when generating the transaction history list for the front end. it just requires another wrinkle.

**Comment by lastmeta** [comment]
**Created from**
https://github.com/moontreeapp/raven_front/issues/6

**Comment by lastmeta** [comment]
not closing because this could use enhancement

**Comment by lastmeta** [comment]
I tried sending today and got this error:
```
I/flutter ( 5987): ----------------FIREBASE CRASHLYTICS----------------I/flutter ( 5987): Concurrent modification during iteration: _LinkedHashMap len:0.
I/flutter ( 5987): #0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:476:7)
I/flutter ( 5987): #1      AddressSubscriptionWaiter.deinitSubscriptionHandles (package:raven_back/waiters/address_subscription.dart:29:72)   
I/flutter ( 5987): <asynchronous suspension>
I/flutter ( 5987): #2      AddressSubscriptionWaiter.setupClientListener.<anonymous closure> (package:raven_back/waiters/address_subscription.dart:38:11)
I/flutter ( 5987): <asynchronous suspension>
I/flutter ( 5987): ----------------------------------------------------
```
not sure if it happens everytime but this means something we changed recently about address_subscription doesn't pull the mempool correctly and therefore the transaction didn't show up in my history, even though it happened.

**Comment by lastmeta** [comment]
this isn't instant but its quick, I'm closing for now, we can reopen if we find its insufficient.
